// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  actionsWrapper: string;
  container: string;
  errorMsg: string;
  header: string;
  inputWrapper: string;
  wrapper: string;
}
export const cssExports: CssExports;
export default cssExports;
