// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  activityAddress: string;
  activityStatus: string;
  addButtonContainer: string;
  btnActive: string;
  btnPrimary: string;
  btnSpinner: string;
  closeButton: string;
  contentContainer: string;
  dialog: string;
  formActivityInfo: string;
  formHeader: string;
  formUserInfo: string;
  inputWrapper: string;
  root: string;
  textArea: string;
}
export const cssExports: CssExports;
export default cssExports;
