// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  inputWrapper: string;
  selectInputContainer: string;
}
export const cssExports: CssExports;
export default cssExports;
