// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'activityAddress': string;
  'activityStatus': string;
  'addButtonContainer': string;
  'btnActive': string;
  'btnCancel': string;
  'btnDisabled': string;
  'btnPrimary': string;
  'btnSpinner': string;
  'closeButton': string;
  'contentContainer': string;
  'dialog': string;
  'dialogForm': string;
  'estimation': string;
  'formActionsContainer': string;
  'formActivityInfo': string;
  'formHeader': string;
  'formInput': string;
  'formSelect': string;
  'formUserInfo': string;
  'inputWrapper': string;
  'textArea': string;
}
export const cssExports: CssExports;
export default cssExports;
