// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'drawer': string;
  'drawerClose': string;
  'drawerOpen': string;
  'hide': string;
  'link': string;
  'list': string;
  'root': string;
  'toolbar': string;
}
export const cssExports: CssExports;
export default cssExports;
