// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'mainNav__linkTitle': string;
  'sideNav': string;
  'sideNav__List': string;
  'sideNav__link': string;
  'sideNav__linkTitle': string;
  'sidebar': string;
  'sidebarIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
