// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addButton': string;
  'buttonsContainer': string;
  'textArea': string;
  'textAreaContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
