// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'errorContainer': string;
  'errorMsg': string;
}
export const cssExports: CssExports;
export default cssExports;
