// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  counter: string;
  mapsContainer: string;
  mapsInnerContainer: string;
  statsContainer: string;
  statsInnerContainer: string;
}
export const cssExports: CssExports;
export default cssExports;
