// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'counter': string;
  'statsContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
