// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'account': string;
  'header': string;
  'logOut': string;
  'logo': string;
  'userInfo': string;
  'userInfoContainer': string;
  'userName': string;
}
export const cssExports: CssExports;
export default cssExports;
