// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  closeButton: string;
  dialogHeader: string;
  flexContainer: string;
  tableCell: string;
  tableHeader: string;
}
export const cssExports: CssExports;
export default cssExports;
