// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  address: string;
  cardActions: string;
  cardContainer: string;
  cardContent: string;
  taskType: string;
}
export const cssExports: CssExports;
export default cssExports;
