// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  addButton: string;
  addButtonContainer: string;
  addNewCardContainer: string;
  container: string;
  dropDisabled: string;
  dropEnabled: string;
}
export const cssExports: CssExports;
export default cssExports;
